version: "3.9"

services:
  backend:
    build: ./server
    environment:
      - PORT=3001
      - NODE_ENV=development
      - API_KEY=changeme
      - ALLOWED_ORIGINS=http://localhost:5173
      - DB_PATH=/data/database.sqlite
    volumes:
      - sqlite_data:/data
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:3001}
        VITE_ENV: ${VITE_ENV:-development}
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:3001}
      - VITE_ENV=${VITE_ENV:-development}
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  sqlite_data:
