name: CI

on:
  push:
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: server/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run tests
        run: npm test
      - name: Build backend
        run: |
          npm run build --if-present
          npm pack
      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: server/*.tgz

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run tests
        run: npm test
      - name: Build frontend
        run: npm run build
      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: frontend/dist

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Install backend dependencies
        working-directory: server
        run: npm ci
      - name: Start backend server
        working-directory: server
        env:
          PORT: 3001
          API_KEY: changeme
          DB_PATH: ${{ github.workspace }}/server/database.sqlite
        run: |
          npm run migrate
          npm start &
          until curl -s http://localhost:3001/ > /dev/null; do sleep 1; done
      - name: Install Playwright browsers
        run: npx playwright install
      - name: Run e2e tests
        env:
          TEST_BASE_URL: http://127.0.0.1:3001
          TEST_API_KEY: changeme
        run: npm run test:e2e

  deploy:
    needs:
      - backend
      - frontend
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend
          path: backend
      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend
          path: frontend
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Implementar comandos de deploy aqui"
