name: Debug Provision

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Check SFTP secrets
        run: |
          echo "🔍 Checking SFTP secrets..."
          for v in SFTP_HOST SFTP_PORT SFTP_USERNAME SFTP_PASSWORD; do
            if [ -z "${!v}" ]; then 
              echo "❌ Missing secret: $v"
            else
              echo "✅ Secret $v is set"
            fi
          done
        env:
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
          SFTP_PORT: ${{ secrets.SFTP_PORT }}
          SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}

      - name: Test SFTP connection
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          source: "README.md"
          target: "/tmp/test-connection.txt"
          strip_components: 0

      - name: Test SSH execution
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          script: |
            echo "🚀 SSH connection test successful!"
            echo "Current directory: $(pwd)"
            echo "User: $(whoami)"
            echo "Test file exists: $(ls -la /tmp/test-connection.txt)"
            echo "✅ Basic SSH test passed"
