name: Deploy Development Environment

on:
  push:
    branches: [develop, dev]
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci
      
    - name: Build frontend for development
      working-directory: ./frontend
      run: npm run build:dev
      env:
        VITE_API_URL: https://dev-api.xml.lojasrealce.shop
        
    - name: Deploy to Dev Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SFTP_HOST }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        port: ${{ secrets.SFTP_PORT }}
        source: "frontend/dist/*"
        target: "/var/www/dev"
        strip_components: 2
        
    - name: Deploy status
      run: |
        echo "✅ Development environment deployed!"
        echo "🌐 Frontend: https://dev.xml.lojasrealce.shop"
        echo "🔌 API: https://dev-api.xml.lojasrealce.shop"
