name: Test Workflow

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test
        run: |
          echo "Workflow funcionando!"
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
